# curl -X POST "http://localhost:8080/api/direct-comparisons/rest-api"
#    -H "Content-Type: application/json"
#    -d '{
#      "sourceOneUrl": "http://localhost:8080/rjp/query?connection=EXAMPLE_DB_1&sqlQuery=select%20*%20from%20customer%20where%20id%3C800",
#      "sourceOneParams": {
#        "authToken": "<SOURCE_API_TOKEN>",
#        "recordsPath": "data.items"
#      },
#      "sourceTwoUrl": "http://source2.api/query?sqlQuery=select%20*%20from%20customer%20where%20id%20in%20(10%2C11)",
#      "sourceTwoParams": {
#        "authToken": "<TARGET_API_TOKEN>",
#        "recordsPath": "data.items"
#      },
#      "comparisonConfig": {
#        "keyFields": ["ID"],
#        "fieldsToCompare": [ "FIRST_NAME", "LAST_NAME" ]
#      }
#    }'
POST http://localhost:8081/api/direct-comparisons/rest-api
Content-Type: application/json

{
      "sourceOneUrl":  "http://localhost:8080/rjp/query?connection=EXAMPLE_DB_1&sqlQuery=select ID,FIRST_NAME,LAST_NAME from customer where id in (1,2)",
      "sourceOneParams": {
        "authToken": "<SOURCE_API_TOKEN>",
        "recordsPath": "data.items"
      },
      "sourceTwoUrl": "http://localhost:8080/rjp/query?connection=EXAMPLE_DB_2&sqlQuery=select * from customer where id in (1,2)",
      "sourceTwoParams": {
        "authToken": "<TARGET_API_TOKEN>",
        "recordsPath": "data.items"
      },
      "comparisonConfig": {
        "keyFields": ["ID"],
        "fieldsToCompare": [ "FIRST_NAME", "LAST_NAME" ]
      }
    }

###
