FROM maven:3.9-eclipse-temurin-21 AS build
WORKDIR /workspace
COPY pom.xml mvnw ./
COPY .mvn .mvn
RUN ./mvnw -DskipTests dependency:go-offline
COPY src src
RUN ./mvnw -DskipTests package

FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /workspace/target/Diffyne-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8081 9001 9002
ENTRYPOINT ["java", "-jar", "app.jar"]
